version: '3.8'

services:
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile  # Use the Dockerfile for building the PHP-FPM container with Xdebug
    container_name: php-blog
    volumes:
      - ./app:/var/www/html  # Mount the app folder
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini  # Mount the Xdebug config
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=userpassword
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=remote_host=host.docker.internal remote_enable=1

    ports:
      - "9004:9004"  # Xdebug listening port
    depends_on:
      - mysql-db  # Ensure MySQL is started before PHP
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: nginx-blog
    volumes:
      - ./app:/var/www/html  # Mount the app folder for Nginx
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
    ports:
      - "8081:80"  # Expose port 8080 to access the app
    depends_on:
      - php-fpm  # Ensure PHP-FPM starts before Nginx
    networks:
      - my_network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-blog
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"  # Expose MySQL port for connections
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
